addons:
   apt:
     sources:
       - git-core
     packages:
       - git
dist: xenial
addons:
  snaps:
    - hugo

language: python
python:
- '3.7'
branches:
  only: 
    - master

script: make gh-pages-on-travisci
