dist: xenial
addons:
  apt:
    sources:
    - git-core
    packages:
    - git

before_install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.58.2/hugo_extended_0.58.2_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.58.2_Linux-64bit.deb

language: python
python:
- '3.7'

branches:
  only: 
    - master

script: make gh-pages-on-travisci
